require_relative "../lib/base"

eval_gem "zaru"
eval_gem "aasm"
eval_gem "pagy"
eval_gem "phonelib"
eval_gem "pagy"
eval_gem "redis"
eval_gem "redis-objects"
eval_gem "pry-rails"
eval_gem "rails-erd"
eval_gem "rubocop"
eval_gem "brypt"
# eval_gem "rails-i18n"
eval_recipe "rspec"
eval_recipe "config"
eval_recipe "action_storage"
# eval_recipe "google-cloud-storage"
